apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: pelotoniq
  labels:
    app: pelotoniq-backend
    component: config
data:
  application.yml: |
    spring:
      profiles:
        active: kubernetes
      datasource:
        url: jdbc:postgresql://postgres-service:5432/pelotoniq
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          idle-timeout: 300000
          connection-timeout: 20000
          validation-timeout: 5000
      jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            format_sql: true
            use_sql_comments: true
      redis:
        host: redis-service
        port: 6379
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 0
      cache:
        type: redis
        redis:
          time-to-live: 3600000
    
    server:
      port: 8080
      servlet:
        context-path: /api
      tomcat:
        max-threads: 200
        accept-count: 100
        max-connections: 8192
    
    management:
      endpoints:
        web:
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        com.pelotoniq: INFO
        org.springframework.security: WARN
        org.hibernate.SQL: WARN
      pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
      file:
        name: /app/logs/application.log
        max-size: 100MB
        max-history: 30
    
    pelotoniq:
      security:
        jwt:
          secret: ${JWT_SECRET}
          expiration: 86400000
        cors:
          allowed-origins: "*"
          allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
          allowed-headers: "*"
      api:
        rate-limit:
          requests-per-minute: 1000
        data-processor:
          url: http://data-processor-service:3001
        ai-services:
          url: http://ai-services-service:5000
      monitoring:
        enabled: true
        metrics:
          enabled: true
        tracing:
          enabled: true